2020-05-03 20:17:27,378 INFO: Microblog startup [in C:\Users\User\Desktop\microblog\app\__init__.py:74]
2020-05-03 20:34:29,168 INFO: Microblog startup [in C:\Users\User\Desktop\microblog\app\__init__.py:74]
2020-05-03 20:36:34,011 INFO: Microblog startup [in C:\Users\User\Desktop\microblog\app\__init__.py:74]
2020-05-03 20:36:54,643 INFO: Microblog startup [in C:\Users\User\Desktop\microblog\app\__init__.py:74]
2020-05-03 20:37:42,712 INFO: Microblog startup [in C:\Users\User\Desktop\microblog\app\__init__.py:74]
2020-05-03 20:39:14,221 INFO: Microblog startup [in C:\Users\User\Desktop\microblog\app\__init__.py:74]
2020-05-03 20:39:24,508 INFO: Microblog startup [in C:\Users\User\Desktop\microblog\app\__init__.py:74]
2020-05-03 20:39:57,526 INFO: Microblog startup [in C:\Users\User\Desktop\microblog\app\__init__.py:74]
2022-02-11 03:43:55,175 INFO: Microblog startup [in /home/ec2-user/environment/webApp/app/__init__.py:74]
2022-02-11 03:52:54,892 INFO: Microblog startup [in /home/ec2-user/environment/webApp/app/__init__.py:74]
2022-02-11 03:56:37,711 INFO: Microblog startup [in /home/ec2-user/environment/webApp/app/__init__.py:74]
2022-02-11 05:23:51,776 INFO: Microblog startup [in /home/ec2-user/environment/webApp/app/__init__.py:74]
2022-02-11 05:24:05,537 ERROR: Exception on /index [GET] [in /usr/local/lib/python3.7/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.7/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/home/ec2-user/environment/webApp/app/main/routes.py", line 38, in index
    prev_url=prev_url)
  File "/usr/local/lib/python3.7/site-packages/flask/templating.py", line 140, in render_template
    ctx.app,
  File "/usr/local/lib/python3.7/site-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/usr/local/lib/python3.7/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/usr/local/lib/python3.7/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/usr/local/lib/python3.7/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/home/ec2-user/environment/webApp/app/templates/index.html", line 1, in top-level template code
    {% extends "base1.html" %}
  File "/usr/local/lib/python3.7/site-packages/flask/templating.py", line 60, in get_source
    return self._get_source_fast(environment, template)
  File "/usr/local/lib/python3.7/site-packages/flask/templating.py", line 89, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: base1.html
2022-02-11 05:24:09,968 ERROR: Exception on /index [GET] [in /usr/local/lib/python3.7/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.7/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/home/ec2-user/environment/webApp/app/main/routes.py", line 38, in index
    prev_url=prev_url)
  File "/usr/local/lib/python3.7/site-packages/flask/templating.py", line 140, in render_template
    ctx.app,
  File "/usr/local/lib/python3.7/site-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/usr/local/lib/python3.7/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/usr/local/lib/python3.7/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/usr/local/lib/python3.7/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/home/ec2-user/environment/webApp/app/templates/index.html", line 1, in top-level template code
    {% extends "base1.html" %}
  File "/usr/local/lib/python3.7/site-packages/flask/templating.py", line 60, in get_source
    return self._get_source_fast(environment, template)
  File "/usr/local/lib/python3.7/site-packages/flask/templating.py", line 89, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: base1.html
2022-02-11 05:26:18,764 INFO: Microblog startup [in /home/ec2-user/environment/webApp/app/__init__.py:74]
2022-02-11 05:33:12,388 INFO: Microblog startup [in /home/ec2-user/environment/webApp/app/__init__.py:74]
2022-02-11 05:51:13,287 INFO: Microblog startup [in /home/ec2-user/environment/webApp/app/__init__.py:74]
2022-02-11 05:52:27,449 INFO: Microblog startup [in /home/ec2-user/environment/webApp/app/__init__.py:74]
2022-02-11 05:54:30,668 INFO: Microblog startup [in /home/ec2-user/environment/webApp/app/__init__.py:74]
2022-02-11 05:54:58,189 INFO: Microblog startup [in /home/ec2-user/environment/webApp/app/__init__.py:74]
2022-02-11 06:01:55,177 INFO: Microblog startup [in /home/ec2-user/environment/webApp/app/__init__.py:74]
2022-02-11 06:34:28,274 INFO: Microblog startup [in /home/ec2-user/environment/webApp/app/__init__.py:74]
2022-02-11 06:35:31,667 INFO: Microblog startup [in /home/ec2-user/environment/webApp/app/__init__.py:74]
